# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Advisor
email: info@theadvisor.eu
description: > # this means to ignore newlines until "baseurl:"
  A MAN'S FIRST REBELLION OCCURS ONCE HE SHEDS CONFINEMENT. CO-EXISTING AS THE
  BROTHER GALLERY TO THE PROVOCATEUR AND EDITED BY ALEX KAZEMI, THE ADVISOR
  HOSTS A VISUAL ARCHIVE OF ORIGINAL HANDWRITTEN LETTERS PENNED BY VENERATED
  MALES WITHIN THE ARTS, WRITTEN TO FELLOW MEN. THESE ARTIFACTS, PUBLISHED ONCE A
  WEEK, EXIST AS PILLARS OF ADVICE, MENTORSHIP, AND PERSONAL ANECDOTES, OFFERING
  A PEEK INTO THE INNER WORLDS OF CULTURE'S MOST PARAMOUNT MALE CREATIVES. BY
  OFFERING THEIR PERSONAL EXPERIENCES AND ADVISEMENT IN PURSUITS OF OCCUPATION,
  LIFE, AND LOVE, THE ADVISOR AIMS TO BRIDGE THE GAP BETWEEN MYTH AND REALITY,
  ALLOWING FOR COUNSEL AND GUIDANCE FROM EACH INDIVIDUAL CREATIVE TO THE READER.
baseurl: "/theadvisor.eu" # the subpath of your site, e.g. /blog
url: "http://theadvisor.eu" # the base hostname & protocol for your site
twitter_username: theadvisor_eu

# Build settings
markdown: kramdown
